name: CI/CD Pipeline

on:
  push:
    branches: [ "develop", "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # === Backend Tests ===
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install backend dependencies
      working-directory: ./backend
      run: |
        pip install -r requirements.txt

    - name: Run backend tests
      working-directory: ./backend
      run: |
        pytest

    # === Frontend Tests ===
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "20"

    - name: Install frontend dependencies
      working-directory: ./frontend
      run: |
        npm install

    - name: Run frontend tests
      working-directory: ./frontend
      run: |
        npm test

    # === Docker Builds ===
    - name: Build Docker images
      run: |
        docker build -t backend:${{ github.sha }} ./backend
        docker build -t frontend:${{ github.sha }} ./frontend

    # === Push to AWS ECR ===
    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Tag and Push Images to ECR
      env:
        AWS_REGION: ap-south-1
        BACKEND_REPO: <your-backend-ecr-url>
        FRONTEND_REPO: <your-frontend-ecr-url>
      run: |
        docker tag backend:${{ github.sha }} $BACKEND_REPO:${{ github.sha }}
        docker tag frontend:${{ github.sha }} $FRONTEND_REPO:${{ github.sha }}
        docker push $BACKEND_REPO:${{ github.sha }}
        docker push $FRONTEND_REPO:${{ github.sha }}
